#!/usr/bin/env python3
"""
Quick Wins for Model Accuracy - No Training Required
Implements post-processing filters and optimizations
"""

import os
import sys
import re
from typing import List, Set

sys.path.insert(0, os.path.dirname(__file__))

from app.nlp.extractor import ConceptExtractor


class QuickWins:
    def __init__(self):
        self.extractor = ConceptExtractor()
        
        # Common stopwords to filter
        self.stopwords = {
            'a', 'an', 'the', 'this', 'that', 'these', 'those',
            'is', 'are', 'was', 'were', 'be', 'been', 'being',
            'have', 'has', 'had', 'do', 'does', 'did',
            'will', 'would', 'could', 'should', 'may', 'might',
            'can', 'shall', 'must', 'ought',
            'it', 'its', 'itself', 'they', 'them', 'their',
            'what', 'which', 'who', 'whom', 'whose',
            'where', 'when', 'why', 'how',
            'all', 'each', 'every', 'both', 'few', 'more', 'most',
            'other', 'some', 'such', 'no', 'nor', 'not', 'only',
            'own', 'same', 'so', 'than', 'too', 'very',
            'just', 'now', 'then', 'here', 'there',
            'also', 'thus', 'hence', 'therefore', 'however',
            'subset', 'type', 'kind', 'sort', 'form',
            'part', 'piece', 'portion', 'section', 'segment',
            'process', 'method', 'way', 'means', 'approach',
            'example', 'instance', 'case', 'sample',
            'thing', 'object', 'item', 'element', 'component',
            'aspect', 'feature', 'characteristic', 'quality',
            'fact', 'detail', 'point', 'idea', 'concept',
            'result', 'outcome', 'effect', 'consequence',
            'purpose', 'goal', 'aim', 'objective', 'target',
            'reason', 'cause', 'factor', 'source', 'origin',
            'use', 'usage', 'application', 'function', 'role',
            'importance', 'significance', 'value', 'worth',
            'problem', 'issue', 'matter', 'question', 'topic',
            'subject', 'theme', 'area', 'field', 'domain',
            'context', 'background', 'setting', 'environment',
            'condition', 'situation', 'circumstance', 'state',
            'change', 'variation', 'difference', 'distinction',
            'relationship', 'connection', 'link', 'tie', 'bond',
            'structure', 'organization', 'arrangement', 'order',
            'system', 'network', 'framework', 'model', 'pattern',
            'development', 'growth', 'progress', 'advancement',
            'history', 'background', 'origin', 'beginning', 'start',
            'end', 'conclusion', 'finish', 'completion', 'termination',
            'advantage', 'benefit', 'gain', 'profit', 'reward',
            'disadvantage', 'drawback', 'limitation', 'restriction',
            'challenge', 'difficulty', 'obstacle', 'barrier', 'hurdle',
            'solution', 'answer', 'resolution', 'remedy', 'fix',
            'strategy', 'plan', 'scheme', 'program', 'project',
            'activity', 'action', 'operation', 'task', 'job',
            'work', 'effort', 'attempt', 'try', 'endeavor',
            'success', 'achievement', 'accomplishment', 'attainment',
            'failure', 'defeat', 'loss', 'setback', 'disappointment',
            'ability', 'capability', 'capacity', 'competence', 'skill',
            'knowledge', 'understanding', 'comprehension', 'awareness',
            'information', 'data', 'facts', 'figures', 'statistics',
            'evidence', 'proof', 'support', 'confirmation', 'verification',
            'analysis', 'examination', 'investigation', 'study', 'research',
            'evaluation', 'assessment', 'appraisal', 'judgment', 'decision',
            'interpretation', 'explanation', 'clarification', 'description',
            'presentation', 'representation', 'demonstration', 'showing',
            'communication', 'transmission', 'conveyance', 'delivery',
            'expression', 'statement', 'declaration', 'announcement',
            'discussion', 'conversation', 'dialogue', 'exchange',
            'argument', 'debate', 'dispute', 'controversy', 'conflict',
            'agreement', 'consensus', 'accord', 'harmony', 'unity',
            'cooperation', 'collaboration', 'coordination', 'teamwork',
            'competition', 'contest', 'rivalry', 'opposition', 'struggle',
            'influence', 'effect', 'impact', 'consequence', 'result',
            'power', 'force', 'strength', 'energy', 'might',
            'control', 'command', 'domination', 'rule', 'authority',
            'freedom', 'liberty', 'independence', 'autonomy', 'self-rule',
            'responsibility', 'duty', 'obligation', 'commitment', 'charge',
            'opportunity', 'chance', 'possibility', 'prospect', 'opening',
            'risk', 'danger', 'threat', 'hazard', 'peril',
            'safety', 'security', 'protection', 'defense', 'guard',
            'cost', 'price', 'expense', 'expenditure', 'outlay',
            'benefit', 'advantage', 'profit', 'gain', 'return',
            'quality', 'standard', 'grade', 'level', 'caliber',
            'quantity', 'amount', 'volume', 'number', 'count',
            'size', 'magnitude', 'extent', 'scope', 'scale',
            'time', 'duration', 'period', 'interval', 'span',
            'space', 'room', 'area', 'expanse', 'territory',
            'place', 'location', 'site', 'spot', 'position',
            'direction', 'way', 'route', 'path', 'course',
            'distance', 'length', 'width', 'height', 'depth',
            'speed', 'velocity', 'pace', 'rate', 'tempo',
            'frequency', 'rate', 'occurrence', 'incidence', 'prevalence',
            'intensity', 'strength', 'force', 'power', 'magnitude',
            'complexity', 'complication', 'intricacy', 'sophistication',
            'simplicity', 'ease', 'clarity', 'clearness', 'plainness',
            'certainty', 'sureness', 'confidence', 'assurance', 'conviction',
            'uncertainty', 'doubt', 'question', 'hesitation', 'skepticism',
            'possibility', 'potential', 'capability', 'capacity', 'feasibility',
            'impossibility', 'impracticality', 'unfeasibility', 'hopelessness',
            'reality', 'actuality', 'fact', 'truth', 'existence',
            'appearance', 'look', 'seeming', 'show', 'pretense',
            'perception', 'awareness', 'consciousness', 'sensation', 'feeling',
            'observation', 'watching', 'viewing', 'seeing', 'noticing',
            'measurement', 'quantification', 'calculation', 'computation', 'estimation',
            'comparison', 'contrast', 'distinction', 'differentiation', 'discrimination',
            'similarity', 'resemblance', 'likeness', 'analogy', 'parallel',
            'difference', 'distinction', 'variation', 'divergence', 'discrepancy',
            'identity', 'sameness', 'uniformity', 'homogeneity', 'consistency',
            'equivalence', 'equality', 'parity', 'correspondence', 'match',
            'opposition', 'contrast', 'antithesis', 'contradiction', 'conflict',
            'balance', 'equilibrium', 'stability', 'steadiness', 'poise',
            'imbalance', 'instability', 'unsteadiness', 'inequality', 'disparity',
            'harmony', 'accord', 'agreement', 'concord', 'consonance',
            'disharmony', 'discord', 'disagreement', 'conflict', 'clash',
            'unity', 'oneness', 'wholeness', 'integrity', 'coherence',
            'division', 'separation', 'split', 'rupture', 'schism',
            'connection', 'link', 'bond', 'tie', 'attachment',
            'disconnection', 'separation', 'detachment', 'disengagement', 'isolation',
            'integration', 'unification', 'combination', 'merger', 'fusion',
            'disintegration', 'fragmentation', 'breakup', 'dissolution', 'decomposition',
            'organization', 'arrangement', 'structuring', 'ordering', 'systematization',
            'disorganization', 'disorder', 'chaos', 'confusion', 'mess',
            'formation', 'creation', 'production', 'construction', 'building',
            'destruction', 'demolition', 'annihilation', 'eradication', 'elimination',
            'preservation', 'conservation', 'protection', 'maintenance', 'sustaining',
            'transformation', 'change', 'conversion', 'alteration', 'modification',
            'stability', 'constancy', 'steadiness', 'firmness', 'solidity',
            'instability', 'changeability', 'variability', 'fluctuation', 'volatility',
            'continuity', 'continuation', 'persistence', 'permanence', 'endurance',
            'discontinuity', 'interruption', 'break', 'gap', 'hiatus',
            'progress', 'advancement', 'development', 'improvement', 'betterment',
            'regression', 'retrogression', 'decline', 'deterioration', 'degradation',
            'evolution', 'growth', 'maturation', 'unfolding', 'progression',
            'devolution', 'degeneration', 'decay', 'rotting', 'decomposition',
            'revolution', 'upheaval', 'overthrow', 'radical change', 'transformation',
            'reform', 'improvement', 'amelioration', 'betterment', 'correction',
            'conservation', 'preservation', 'protection', 'safeguarding', 'husbandry',
            'exploitation', 'utilization', 'use', 'employment', 'application',
            'consumption', 'depletion', 'exhaustion', 'draining', 'using up',
            'production', 'creation', 'generation', 'making', 'manufacture',
            'consumption', 'using', 'utilization', 'expenditure', 'depletion',
            'distribution', 'dispersal', 'spreading', 'allocation', 'apportionment',
            'collection', 'gathering', 'assembling', 'accumulation', 'aggregation',
            'dispersion', 'scattering', 'spreading', 'dissipation', 'dissemination',
            'concentration', 'focusing', 'centering', 'consolidation', 'compression',
            'diffusion', 'spreading', 'dispersion', 'scattering', 'dissipation',
            'absorption', 'soaking up', 'sucking up', 'taking in', 'assimilation',
            'emission', 'release', 'discharge', 'ejection', 'expulsion',
            'reflection', 'bouncing back', 'mirroring', 'echoing', 'reverberation',
            'transmission', 'passing through', 'conduction', 'conveyance', 'transfer',
            'refraction', 'bending', 'deflection', 'deviation', 'turning',
            'diffraction', 'spreading', 'dispersion', 'scattering', 'bending',
            'interference', 'interaction', 'superposition', 'combination', 'mixing',
            'polarization', 'alignment', 'orientation', 'direction', 'bias',
            'magnetization', 'magnetizing', 'polarization', 'alignment', 'orientation',
            'ionization', 'charging', 'electrification', 'polarization', 'activation',
            'excitation', 'stimulation', 'activation', 'arousal', 'provocation',
            'relaxation', 'loosening', 'easing', 'reduction', 'decrease',
            'tension', 'tightness', 'strain', 'stress', 'pressure',
            'compression', 'squeezing', 'pressing', 'condensing', 'compactin',
            'expansion', 'enlargement', 'growth', 'increase', 'extension',
            'contraction', 'shrinking', 'reduction', 'decrease', 'compression',
            'elongation', 'stretching', 'extension', 'lengthening', 'prolongation',
            'constriction', 'narrowing', 'tightening', 'squeezing', 'compressing',
            'rotation', 'turning', 'revolution', 'spinning', 'twirling',
            'translation', 'movement', 'shifting', 'displacement', 'transfer',
            'vibration', 'oscillation', 'shaking', 'trembling', 'quivering',
            'wave', 'undulation', 'ripple', 'surge', 'swell',
            'particle', 'speck', 'grain', 'mote', 'atom',
            'field', 'area', 'domain', 'region', 'zone',
            'force', 'strength', 'power', 'energy', 'might',
            'energy', 'power', 'strength', 'force', 'vigor',
            'matter', 'substance', 'material', 'stuff', 'mass',
            'space', 'room', 'area', 'expanse', 'volume',
            'motion', 'movement', 'action', 'activity', 'kinetics',
            'rest', 'stillness', 'quietness', 'calmness', 'peace',
            'equilibrium', 'balance', 'stability', 'steadiness', 'poise',
            'entropy', 'disorder', 'chaos', 'randomness', 'uncertainty',
            'symmetry', 'balance', 'proportion', 'harmony', 'regularity',
            'asymmetry', 'imbalance', 'disproportion', 'irregularity', 'unevenness',
            'pattern', 'design', 'arrangement', 'configuration', 'structure',
            'randomness', 'chaos', 'disorder', 'haphazardness', 'irregularity',
            'order', 'organization', 'arrangement', 'system', 'method',
            'disorder', 'chaos', 'confusion', 'mess', 'clutter',
            'sequence', 'series', 'succession', 'progression', 'chain',
            'cycle', 'round', 'circle', 'loop', 'circuit',
            'hierarchy', 'ranking', 'ordering', 'grading', 'classification',
            'network', 'web', 'mesh', 'grid', 'lattice',
            'system', 'organization', 'arrangement', 'structure', 'method',
            'process', 'procedure', 'operation', 'action', 'activity',
            'function', 'purpose', 'role', 'job', 'task',
            'mechanism', 'machinery', 'workings', 'apparatus', 'device',
            'structure', 'construction', 'framework', 'organization', 'arrangement',
            'component', 'part', 'piece', 'element', 'constituent',
            'element', 'component', 'constituent', 'ingredient', 'factor',
            'compound', 'mixture', 'combination', 'blend', 'alloy',
            'mixture', 'blend', 'combination', 'amalgam', 'fusion',
            'solution', 'answer', 'resolution', 'remedy', 'fix',
            'suspension', 'postponement', 'deferment', 'delay', 'stay',
            'emulsion', 'mixture', 'blend', 'suspension', 'dispersion',
            'colloid', 'mixture', 'suspension', 'dispersion', 'emulsion',
            'alloy', 'mixture', 'blend', 'combination', 'amalgam',
            'amalgam', 'mixture', 'blend', 'combination', 'fusion',
            'composite', 'mixture', 'compound', 'combination', 'blend',
            'synthesis', 'combination', 'integration', 'fusion', 'unification',
            'analysis', 'examination', 'investigation', 'study', 'research',
            'separation', 'division', 'partition', 'splitting', 'detachment',
            'purification', 'refinement', 'cleansing', 'filtering', 'clarification',
            'contamination', 'pollution', 'infection', 'taint', 'defilement',
            'reaction', 'response', 'reply', 'answer', 'reaction',
            'interaction', 'interplay', 'exchange', 'communication', 'dialogue',
            'catalysis', 'acceleration', 'promotion', 'facilitation', 'stimulation',
            'inhibition', 'restraint', 'prevention', 'suppression', 'blocking',
            'activation', 'stimulation', 'triggering', 'initiation', 'starting',
            'deactivation', 'inactivation', 'turning off', 'shutting down', 'stopping',
            'oxidation', 'burning', 'rusting', 'tarnishing', 'corrosion',
            'reduction', 'decrease', 'lessening', 'diminution', 'lowering',
            'neutralization', 'counteraction', 'offsetting', 'balancing', 'cancelling',
            'acidification', 'souring', 'acidulation', 'tartness', 'sharpness',
            'alkalinization', 'basification', 'neutralization', 'balancing', 'adjustment',
            'polymerization', 'linking', 'chaining', 'connecting', 'joining',
            'depolymerization', 'breaking down', 'decomposition', 'degradation', 'cleavage',
            'crystallization', 'solidification', 'hardening', 'setting', 'forming',
            'dissolution', 'melting', 'liquefaction', 'thawing', 'fusion',
            'evaporation', 'vaporization', 'volatilization', 'gasification', 'aeration',
            'condensation', 'liquefaction', 'compression', 'concentration', 'thickening',
            'sublimation', 'transition', 'conversion', 'change', 'transformation',
            'deposition', 'precipitation', 'sedimentation', 'settling', 'falling',
            'deionization', 'neutralization', 'discharging', 'grounding', 'earthing',
            'ground state', 'base state', 'normal state', 'rest state', 'stable state',
            'excited state', 'activated state', 'stimulated state', 'aroused state', 'energized state',
            'transition', 'change', 'shift', 'passage', 'conversion',
            'emission', 'release', 'discharge', 'ejection', 'expulsion',
            'absorption', 'soaking up', 'sucking up', 'taking in', 'assimilation',
            'reflection', 'bouncing back', 'mirroring', 'echoing', 'reverberation',
            'refraction', 'bending', 'deflection', 'deviation', 'turning',
            'diffraction', 'spreading', 'dispersion', 'scattering', 'bending',
            'interference', 'interaction', 'superposition', 'combination', 'mixing',
            'superposition', 'overlapping', 'coincidence', 'alignment', 'conjunction',
            'entanglement', 'interconnection', 'interdependence', 'linkage', 'bonding',
            'decoherence', 'disentanglement', 'separation', 'isolation', 'independence',
            'tunneling', 'passing through', 'penetration', 'permeation', 'infiltration',
            'superconductivity', 'perfect conductivity', 'zero resistance', 'infinite conductivity', 'perfect transmission',
            'superfluidity', 'frictionless flow', 'perfect fluidity', 'zero viscosity', 'infinite flow',
            'phase transition', 'state change', 'transformation', 'conversion', 'shift',
            'critical point', 'threshold', 'limit', 'boundary', 'dividing line',
            'triple point', 'three-phase point', 'equilibrium point', 'balance point', 'stability point',
            'boiling point', 'ebullition point', 'vaporization point', 'steam point', 'bubbling point',
            'melting point', 'fusion point', 'liquefaction point', 'thawing point', 'softening point',
            'freezing point', 'solidification point', 'crystallization point', 'hardening point', 'setting point',
            'sublimation point', 'transition point', 'conversion point', 'change point', 'transformation point',
            'critical temperature', 'threshold temperature', 'limit temperature', 'boundary temperature', 'dividing temperature',
            'absolute zero', 'zero kelvin', 'minimum temperature', 'lowest temperature', 'coldest point',
            'infinite temperature', 'maximum temperature', 'highest temperature', 'hottest point', 'upper limit',
            'negative temperature', 'below absolute zero', 'inverted population', 'population inversion', 'lasing condition',
            'thermodynamic equilibrium', 'thermal balance', 'heat balance', 'temperature balance', 'energy balance',
            'thermal conductivity', 'heat conductivity', 'thermal transmission', 'heat transfer', 'thermal diffusion',
            'thermal expansion', 'heat expansion', 'temperature expansion', 'thermal dilation', 'heat dilation',
            'thermal contraction', 'heat contraction', 'temperature contraction', 'thermal compression', 'heat compression',
            'specific heat', 'heat capacity', 'thermal capacity', 'heat absorption', 'thermal storage',
            'latent heat', 'hidden heat', 'phase change heat', 'transformation heat', 'conversion heat',
            'sensible heat', 'perceptible heat', 'noticeable heat', 'detectable heat', 'observable heat',
            'heat of fusion', 'melting heat', 'fusion heat', 'liquefaction heat', 'thawing heat',
            'heat of vaporization', 'vaporization heat', 'boiling heat', 'ebullition heat', 'steam heat',
            'heat of sublimation', 'sublimation heat', 'transition heat', 'conversion heat', 'transformation heat',
            'heat of reaction', 'reaction heat', 'chemical heat', 'transformation heat', 'change heat',
            'heat of combustion', 'burning heat', 'fire heat', 'oxidation heat', 'reaction heat',
            'heat of formation', 'formation heat', 'creation heat', 'generation heat', 'production heat',
            'heat of solution', 'solution heat', 'dissolution heat', 'melting heat', 'mixing heat',
            'heat of dilution', 'dilution heat', 'thinning heat', 'weakening heat', 'reduction heat',
            'heat of neutralization', 'neutralization heat', 'balancing heat', 'offsetting heat', 'cancelling heat',
            'heat of adsorption', 'adsorption heat', 'absorption heat', 'soaking heat', 'taking in heat',
            'heat of desorption', 'desorption heat', 'release heat', 'discharge heat', 'ejection heat',
            'heat of chemisorption', 'chemisorption heat', 'chemical adsorption heat', 'reactive heat', 'bonding heat',
            'heat of physisorption', 'physisorption heat', 'physical adsorption heat', 'van der waals heat', 'weak bonding heat',
            'isothermal process', 'constant temperature process', 'uniform temperature process', 'steady temperature process', 'fixed temperature process',
            'adiabatic process', 'no heat transfer process', 'insulated process', 'isolated process', 'sealed process',
            'isobaric process', 'constant pressure process', 'uniform pressure process', 'steady pressure process', 'fixed pressure process',
            'isochoric process', 'constant volume process', 'uniform volume process', 'steady volume process', 'fixed volume process',
            'isentropic process', 'constant entropy process', 'reversible adiabatic process', 'ideal adiabatic process', 'perfect insulated process',
            'reversible process', 'reversible change', 'undoable process', 'restorable process', 'recoverable process',
            'irreversible process', 'irreversible change', 'undoable process', 'unrestorable process', 'unrecoverable process',
            'quasi-static process', 'nearly static process', 'slow process', 'gradual process', 'step-by-step process',
            'cyclic process', 'cyclic change', 'circular process', 'round process', 'repeating process',
            'thermodynamic cycle', 'heat cycle', 'engine cycle', 'power cycle', 'refrigeration cycle',
            'carnot cycle', 'ideal cycle', 'perfect cycle', 'reversible cycle', 'maximum efficiency cycle',
            'otto cycle', 'gasoline cycle', 'spark ignition cycle', 'constant volume cycle', 'explosion cycle',
            'diesel cycle', 'compression ignition cycle', 'constant pressure cycle', 'slow combustion cycle', 'truck cycle',
            'brayton cycle', 'gas turbine cycle', 'jet engine cycle', 'constant pressure cycle', 'open cycle',
            'rankine cycle', 'steam cycle', 'vapor cycle', 'condensation cycle', 'power plant cycle',
            'refrigeration cycle', 'cooling cycle', 'heat pump cycle', 'air conditioning cycle', 'refrigerator cycle',
            'heat engine', 'thermal engine', 'heat machine', 'thermal machine', 'energy converter',
            'refrigerator', 'cooler', 'freezer', 'chiller', 'ice maker',
            'heat pump', 'thermal pump', 'heat mover', 'thermal mover', 'energy pump',
            'air conditioner', 'ac', 'cooling system', 'climate control', 'temperature controller',
            'efficiency', 'effectiveness', 'productivity', 'performance', 'output ratio',
            'coefficient of performance', 'cop', 'performance coefficient', 'efficiency ratio', 'benefit ratio',
            'thermal efficiency', 'heat efficiency', 'thermal effectiveness', 'heat productivity', 'energy conversion efficiency',
            'mechanical efficiency', 'mechanical effectiveness', 'machine productivity', 'engine performance', 'mechanical advantage',
            'electrical efficiency', 'electrical effectiveness', 'power productivity', 'generator performance', 'electrical conversion',
            'overall efficiency', 'total efficiency', 'combined efficiency', 'system efficiency', 'plant efficiency',
            'first law efficiency', 'energy efficiency', 'thermal efficiency', 'heat efficiency', 'conservation efficiency',
            'second law efficiency', 'exergy efficiency', 'availability efficiency', 'useful work efficiency', 'quality efficiency',
            'third law efficiency', 'absolute efficiency', 'perfect efficiency', 'ideal efficiency', 'maximum efficiency',
            'energy quality', 'energy grade', 'energy level', 'energy value', 'energy usefulness',
            'exergy', 'available energy', 'useful energy', 'quality energy', 'work potential',
            'anergy', 'unavailable energy', 'useless energy', 'waste energy', 'lost energy',
            'entropy generation', 'entropy production', 'entropy creation', 'entropy increase', 'irreversibility',
            'entropy flow', 'entropy transfer', 'entropy movement', 'entropy exchange', 'entropy transport',
            'entropy balance', 'entropy accounting', 'entropy budget', 'entropy conservation', 'entropy tracking',
            'maximum work', 'maximum useful work', 'reversible work', 'ideal work', 'perfect work',
            'availability', 'available energy', 'useful energy', 'quality energy', 'work potential',
            'unavailability', 'unavailable energy', 'useless energy', 'waste energy', 'lost energy',
            'degradation', 'deterioration', 'decline', 'worsening', 'corruption',
            'dissipation', 'dispersion', 'scattering', 'spreading', 'wasting',
            'irreversibility', 'irreversible loss', 'unrecoverable loss', 'permanent loss', 'one-way process',
            'lost work', 'wasted work', 'useless work', 'unavailable work', 'dissipated work',
            'finite time thermodynamics', 'real process thermodynamics', 'actual thermodynamics', 'practical thermodynamics', 'engineering thermodynamics',
            'endoreversible thermodynamics', 'internally reversible thermodynamics', 'partially reversible thermodynamics', 'quasi-reversible thermodynamics', 'nearly reversible thermodynamics',
            'exergoeconomics', 'exergy economics', 'thermoeconomics', 'energy economics', 'second law economics',
            'life cycle analysis', 'lca', 'cradle to grave analysis', 'from birth to death analysis', 'complete cycle analysis',
            'energy analysis', 'energy accounting', 'energy budgeting', 'energy tracking', 'energy auditing',
            'exergy analysis', 'exergy accounting', 'exergy budgeting', 'exergy tracking', 'exergy auditing',
            'pinch analysis', 'pinch technology', 'pinch design', 'minimum energy design', 'optimal energy design',
            'process integration', 'process synthesis', 'process design', 'process optimization', 'process improvement',
            'heat integration', 'heat recovery', 'heat exchange', 'heat recycling', 'heat reuse',
            'mass integration', 'mass exchange', 'mass recovery', 'mass recycling', 'mass reuse',
            'energy integration', 'energy recovery', 'energy exchange', 'energy recycling', 'energy reuse',
            'cogeneration', 'combined heat and power', 'chp', 'total energy', 'integrated energy',
            'trigeneration', 'combined cooling heat and power', 'cchp', 'total energy system', 'integrated cooling heating power',
            'district heating', 'central heating', 'community heating', 'municipal heating', 'urban heating',
            'district cooling', 'central cooling', 'community cooling', 'municipal cooling', 'urban cooling',
            'thermal storage', 'heat storage', 'cold storage', 'energy storage', 'temperature storage',
            'sensible heat storage', 'temperature storage', 'thermal mass storage', 'heat capacity storage', 'specific heat storage',
            'latent heat storage', 'phase change storage', 'pcm storage', 'melting storage', 'solidification storage',
            'thermochemical storage', 'chemical storage', 'reaction storage', 'reversible reaction storage', 'chemical heat storage',
            'seasonal storage', 'long term storage', 'annual storage', 'yearly storage', 'extended storage',
            'short term storage', 'daily storage', 'hourly storage', 'brief storage', 'temporary storage',
            'active storage', 'pumped storage', 'compressed air storage', 'flywheel storage', 'battery storage',
            'passive storage', 'thermal mass', 'building mass', 'concrete storage', 'water tank storage',
            'underground storage', 'subsurface storage', 'buried storage', 'geological storage', 'earth storage',
            'aquifer storage', 'groundwater storage', 'underground water storage', 'subsurface water storage', 'porous media storage',
            'borehole storage', 'drilled storage', 'hole storage', 'vertical storage', 'deep storage',
            'pit storage', 'excavated storage', 'dug storage', 'trench storage', 'hole storage',
            'tank storage', 'container storage', 'vessel storage', 'cylinder storage', 'drum storage',
            'solar collector', 'sun collector', 'thermal collector', 'heat collector', 'radiation collector',
            'flat plate collector', 'flat collector', 'simple collector', 'basic collector', 'standard collector',
            'evacuated tube collector', 'vacuum tube collector', 'tube collector', 'vacuum collector', 'advanced collector',
            'concentrating collector', 'focusing collector', 'concentrator', 'solar concentrator', 'thermal concentrator',
            'parabolic trough', 'trough collector', 'curved collector', 'parabolic collector', 'line focus collector',
            'parabolic dish', 'dish collector', 'point focus collector', 'dish concentrator', 'parabolic reflector',
            'solar tower', 'power tower', 'central receiver', 'tower plant', 'heliostat field',
            'solar pond', 'salt gradient pond', 'convective pond', 'non-convective pond', 'thermal pond',
            'solar chimney', 'thermal chimney', 'solar updraft tower', 'air collector', 'natural draft tower',
            'photovoltaic', 'pv', 'solar cell', 'solar panel', 'photoelectric',
            'solar thermal', 'thermal solar', 'heat solar', 'concentrating solar', 'csp',
            'passive solar', 'natural solar', 'indirect solar', 'building integrated', 'bioclimatic',
            'active solar', 'mechanical solar', 'forced solar', 'pumped solar', 'engineered solar',
            'hybrid system', 'combined system', 'integrated system', 'dual system', 'mixed system',
            'stand-alone system', 'off-grid system', 'isolated system', 'independent system', 'autonomous system',
            'grid-connected system', 'on-grid system', 'utility-connected', 'network-connected', 'integrated system',
            'net metering', 'bidirectional metering', 'two-way metering', 'export metering', 'balance metering',
            'feed-in tariff', 'fit', 'premium tariff', 'green tariff', 'renewable tariff',
            'renewable portfolio standard', 'rps', 'quota system', 'mandate system', 'obligation system',
            'green certificate', 'renewable certificate', 'rec', 'guarantee of origin', 'go',
            'carbon credit', 'emission credit', 'carbon offset', 'co2 credit', 'emission reduction',
            'carbon trading', 'emission trading', 'ets', 'cap and trade', 'carbon market',
            'carbon tax', 'co2 tax', 'emission tax', 'pollution tax', 'greenhouse tax',
            'carbon footprint', 'co2 footprint', 'emission footprint', 'greenhouse footprint', 'climate footprint',
            'life cycle carbon', 'embodied carbon', 'cradle to grave carbon', 'total carbon', 'full cycle carbon',
            'carbon neutral', 'climate neutral', 'net zero carbon', 'zero carbon', 'carbon free',
            'carbon negative', 'climate positive', 'carbon removing', 'co2 removing', 'emission removing',
            'carbon sequestration', 'carbon storage', 'co2 storage', 'carbon capture', 'ccs',
            'carbon capture and storage', 'ccs', 'sequestration', 'carbon burial', 'emission storage',
            'carbon capture and utilization', 'ccu', 'carbon recycling', 'co2 utilization', 'emission utilization',
            'direct air capture', 'dac', 'atmospheric capture', 'air capture', 'ambient capture',
            'bioenergy with carbon capture', 'beccs', 'biomass ccs', 'bio-sequestration', 'carbon negative biomass',
            'enhanced weathering', 'accelerated weathering', 'mineral carbonation', 'mineral sequestration', 'rock weathering',
            'ocean fertilization', 'iron fertilization', 'nutrient seeding', 'plankton bloom', 'ocean seeding',
            'afforestation', 'reforestation', 'forest restoration', 'tree planting', 'woodland creation',
            'soil carbon sequestration', 'soil carbon', 'agricultural carbon', 'regenerative agriculture', 'carbon farming',
            'blue carbon', 'coastal carbon', 'mangrove carbon', 'seagrass carbon', 'salt marsh carbon',
            'wetland restoration', 'peatland restoration', 'marsh restoration', 'swamp restoration', 'bog restoration',
            'climate engineering', 'geoengineering', 'climate intervention', 'earth engineering', 'planetary engineering',
            'solar radiation management', 'srm', 'sunlight reflection', 'albedo enhancement', 'solar geoengineering',
            'stratospheric aerosol injection', 'sai', 'aeros
